language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python ./poestore/build.py
notifications:
  email:
    on_success: never
    on_failure: always
    on_start: never
    on_cancel: never
    on_error: always
